---
title: "squishGrype"
author: "Sabrina Hendricks && Gabe Cowley"
date: "2023-06-14 && 2023-07-11"
output: html_document
---

```{r setup}
library(jsonlite)
library(tidyverse)
library(here)

```

```{r}
# To call the appropriate Grype version folders that hold the images
grype_path = paste0("YOUR PATH",
                    "/reu-2023-cloud-tools/02_Preprocessing/02b_squish/01_input/Grype/")

grype_list <- list.files(grype_path)
```

```{r message=FALSE, warning=FALSE}
# Going through each Grype version in sequence
for (grype_version in grype_list) {
  print(grype_version)
  csv_file_path <- paste0(grype_path, grype_version)
  file_list <- list.files(csv_file_path)
  data_list <- list()
  
  # Extract the image name from the file name
  image_name <- str_remove(file_list, "Grype.csv")
  
  # These files are our csv files from the scanned images
  for (i in seq_along(file_list)) {
    file <- file_list[i]
    
    # Create an empty list to store the processed data frames
    # data_list <- list()  # Remove this line
    
    data <- read_csv(here(csv_file_path, file))
    
    # Check if the data frame is empty
    if (is.na(data[[1]])) {
      # Create a new data frame with desired column names and values
      empty_data <- data.frame(
        imageName = image_name[i],
        vulnerabilityID = "NA",
        count = 0,
        severity = "NA"
      )
      
      # Append the empty data frame to the list
      data_list[[file]] <- empty_data
    } else {
      # Remove leading and trailing whitespace from column names
      col_names <- trimws(colnames(data))
      col_names <-
        make.names(col_names, unique = TRUE, allow = TRUE)
      colnames(data) <- col_names
      
      # Group the data by column names and calculate the count
      processed_data <- data %>%
        group_by(vulnerabilityID, severity) %>%
        summarise(count = n()) %>%
        ungroup() %>%
        mutate(imageName = image_name[i])
      
      # Append the processed data frame to the list
      data_list[[file]] <- processed_data
    }
  }
  
  # Bind the data
  master_data <- bind_rows(data_list)
  
  # Reorder the columns
  master_data <- select(master_data, imageName, everything())
  
  # Specify the directory path
  output_file_path <- here(
    "02_Preprocessing",
    "02b_squish",
    "04_product",
    "Grype",
    grype_version,
    "master_dataGrype.csv"
  )
  
  # Save the data frame as a CSV file
  write.csv(master_data, file = output_file_path, row.names = FALSE)
}

```

