---
title: "json_to_csvGrype"
output: html_document
date: "2023-06-13"
---

## Setup
```{r setup}
library(here)

# Set the root directory using the here package
root_dir <- here()

library(jsonlite)
#library(tidyverse)
library(Dict)
library(stringr)
```

```{r}
# To call the appropriate Grype version folders that hold the images
grype_path = paste0(
  "YOUR PATH",
  "/reu-2023-cloud-tools/02_Preprocessing/02a_jsonTocsv/01_input/Grype/"
)

#list of all the folders that correspond to specific grype versions
grype_list <- list.files(grype_path)

```

```{r}
#for each grype version,each image, convert json files to csv
for (grype_version in grype_list) {
  image_path = paste0(grype_path, grype_version, "/")
  image_list <- list.files(image_path)
  print(grype_version)
  for (image in image_list) {
    # Initialize data
    json_data <-
      tryCatch(
        jsonlite::fromJSON(txt = readLines(
          here(
            "02_Preprocessing/02a_jsonTocsv/01_input/Grype",
            grype_version,
            image
          )
        )),
        error = function(e)
          NULL
      )
    
    packageName <- json_data$matches$artifact$name
    vulnerabilityID <- json_data$matches$vulnerability$id
    severity <- json_data$matches$vulnerability$severity
    
    # If our image has no vulnerabilities
    if (is.null(vulnerabilityID)) {
      packageName <- NA
      vulnerabilityID <- NA
      severity <- NA
    }
    
    data <- data.frame(packageName, vulnerabilityID, severity)
    
    
    #this next section is separate, just updating the vulnerability list, make function to separate it out.
    
    
    ### Library Equivalent Vulnerabilities List
    # Load the CSV file
    
    connectedVulnerabilities <-
      read.csv(
        here(
          "02_Preprocessing",
          "02a_jsonTocsv",
          "03_incremental",
          "connectedVulnerabilityIDs.csv"
        )
      )
    
    #BY THE WAY: Don't worry about this error message from the below "if statement"
    #       Error in if (vulnerabilityID[i] != relatedVulnerabilitiesID[i]) { :
    #         missing value where TRUE/FALSE needed
    # Any time that this error is applicable, we don't need an addition to the code
    
    if (length(json_data$matches$vulnerability$id) != 0) {
      for (i in 1:length(json_data$matches$vulnerability$id)) {
        vulnerabilityID <- json_data$matches$vulnerability$id[i]
        relatedVulnerabilitiesID <-
          json_data$matches$relatedVulnerabilities[[i]]$id
        severity <-
          json_data$matches$relatedVulnerabilities[[i]]$severity
        
        if (!(is.null(vulnerabilityID) ||
              is.na(vulnerabilityID)) &&
            (any(!is.null(relatedVulnerabilitiesID)) &&
             any(!is.na(relatedVulnerabilitiesID)))) {
          if (any(vulnerabilityID != relatedVulnerabilitiesID)) {
            if (!vulnerabilityID %in% connectedVulnerabilities$main_vulnerability) {
              # Add a new row to the connected vulnerabilities data frame
              newRow <-
                data.frame(
                  main_vulnerability = vulnerabilityID,
                  related_vulnerability = relatedVulnerabilitiesID,
                  severity = severity
                )
              connectedVulnerabilities <-
                rbind(connectedVulnerabilities, newRow)
              
              # Update an existing row
              connectedVulnerabilities$main_vulnerability[connectedVulnerabilities$related_vulnerability == "related_vulnerability"] <-
                "updated_vulnerability"
              
              # Write the data frame to the CSV file
              write.csv(
                connectedVulnerabilities,
                file = here(
                  "02_Preprocessing",
                  "02a_jsonTocsv",
                  "03_incremental",
                  "connectedVulnerabilityIDs.csv"
                ),
                row.names = FALSE
              )
              
            }
          }
        }
      }
    }
    
    # Specify the directory path
    directory_path <-
      here("02_Preprocessing",
           "02a_jsonTocsv",
           "04_product",
           "Grype",
           grype_version,
           "/")
    
    # Since the output isn't a json, that shouldn't be in the name
    image_name <- str_remove(image, ".json")
    
    # Specify the output file name as a variable
    output_name <- paste0(image_name, "Grype.csv")
    
    # Concatenate the directory path and output file name
    file_path <- here(directory_path, output_name)
    
    # Save the data frame as a CSV file in the specified directory
    write.csv(data, file = file_path, row.names = FALSE)
  }
}
```